### PR TITLE
removed the use of the scss lib as its broken (no styling for now)

### PR DESCRIPTION
**Pull request by davidmort**
# Motivation and Context
it looks the the pyscss lib is broken (https://travis-ci.org/github/Kronuz/pyScss) and we can't build a new version of the ops tool because of this, for now i've stripped it out so we can carry on until we find a proper fix, all this means is there wont be much styling

# What has changed
- removed pyscss from Pipfile
- regenerated Pipfile.lock
- removed the use of the scss lib from app/__init__.py

# How to test?
- build locally by running make build then make docker
- run docker dev enviroment and test you can still load a sample and set up an action plan

### CODE REVIEW

**Comment by davidmort** [comment]
[Investigate ops tool package issues](https://trello.com/c/mjn1Vnov/731-investigate-ops-tool-package-issues)

**Review by AdamHawtin — APPROVED** [review]
👍 Doesn't *look* good to me but it works!

**Review by ryangrundy7 — COMMENTED** [review]
Might be worth updating qid-batcher runner to it's latest version as well https://github.com/ONSdigital/census-rm-qid-batch-runner/releases

**Comment by davidmort** [comment]
> Might be worth updating qid-batcher runner to it's latest version as well https://github.com/ONSdigital/census-rm-qid-batch-runner/releases

yes good point will do that now 👍

**Review by ryangrundy7 — DISMISSED** [review]
Travis failing due to a unit test failure

**Review by NickGrantX — APPROVED** [review]
Ryan was saying that we've removed a method which was needed, but if this is good enough to get the testers able to load samples then happy to approve.

**Comment by davidmort** [comment]
> Travis failing due to a unit test failure

just committed a fix for that and have bumped the qid-batch-runner version

**Comment by davidmort** [comment]
> Ryan was saying that we've removed a method which was needed, but if this is good enough to get the testers able to load samples then happy to approve.

@NickGrantONS @ryangrundy7 what method was this?

**Pull request merged**
