### PR TITLE
adding new reminder pack codes

### PR DESCRIPTION
**Pull request by apolloakora**
# Motivation and Context
Adding two new reminder pack codes

# What has changed
Two new pack codes have been added mainly as enums throughout the software.

### CODE REVIEW

**Comment by apolloakora** [comment]
[Add reminder pack codes (3)](https://trello.com/c/6qsTSOf5/1118-add-reminder-pack-codes-3)

**Review by NickGrantX — APPROVED** [review]

**Review by NickGrantX — CHANGES_REQUESTED** [review]
Missing `P_RL_2RL1` and `P_RL_2RL2B`

**Review by NickGrantX — CHANGES_REQUESTED** [review]
Missing pack codes: `P_RL_2RL1`, `P_RL_2RL2B`

**Review by NickGrantX — APPROVED** [review]

**Review by AdamHawtin — CHANGES_REQUESTED** [review]
This doesn't look like all the codes being added elsewhere, I count 8 being added in the print file service.

**Review by AdamHawtin — APPROVED** [review]

**Pull request merged**
